#ifndef DEFS_H
#define DEFS_H

#define MAX_STRING_TAMANHO 100
#define TAMANHO_CABECALHO_INDICE 12
#define TAMANHO_REGISTRO_INDICE 12
#define TAMANHO_CABECALHO_PESSOA 17
#define TAMANHO_CABECALHO_SEGUE 9
#define TAMANHO_REGISTRO_SEGUE 30

#endif